import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { CONFIG } from '../config.js';

const execAsync = promisify(exec);

export interface SubtitleSegment {
  index: number;
  start: number; // in seconds
  end: number;   // in seconds
  text: string;
}

export interface SubtitleResult {
  srtPath: string;
  vttPath: string;
  srtUrl: string;
  vttUrl: string;
  segments: SubtitleSegment[];
}

export class SubtitleService {
  constructor() {
    fs.mkdirSync(CONFIG.SUBTITLES_DIR, { recursive: true });
  }

  /**
   * Format seconds into SRT timestamp: HH:MM:SS,mmm
   */
  private formatTimestampSRT(seconds: number): string {
    const totalMs = Math.max(0, Math.floor(seconds * 1000));
    const hrs = Math.floor(totalMs / 3600000);
    const mins = Math.floor((totalMs % 3600000) / 60000);
    const secs = Math.floor((totalMs % 60000) / 1000);
    const ms = totalMs % 1000;

    const pad = (n: number, z: number = 2) => n.toString().padStart(z, '0');
    return `${pad(hrs)}:${pad(mins)}:${pad(secs)},${pad(ms, 3)}`;
  }

  /**
   * Format seconds into WebVTT timestamp: HH:MM:SS.mmm
   */
  private formatTimestampVTT(seconds: number): string {
    const totalMs = Math.max(0, Math.floor(seconds * 1000));
    const hrs = Math.floor(totalMs / 3600000);
    const mins = Math.floor((totalMs % 3600000) / 60000);
    const secs = Math.floor((totalMs % 60000) / 1000);
    const ms = totalMs % 1000;

    const pad = (n: number, z: number = 2) => n.toString().padStart(z, '0');
    return `${pad(hrs)}:${pad(mins)}:${pad(secs)}.${pad(ms, 3)}`;
  }

  /**
   * Generates SRT string representation
   */
  public generateSRT(segments: SubtitleSegment[]): string {
    return segments
      .map(
        (seg) =>
          `${seg.index}\n${this.formatTimestampSRT(seg.start)} --> ${this.formatTimestampSRT(
            seg.end
          )}\n${seg.text}\n`
      )
      .join('\n');
  }

  /**
   * Generates WebVTT string representation
   */
  public generateVTT(segments: SubtitleSegment[]): string {
    const body = segments
      .map(
        (seg) =>
          `${seg.index}\n${this.formatTimestampVTT(seg.start)} --> ${this.formatTimestampVTT(
            seg.end
          )}\n${seg.text}\n`
      )
      .join('\n');

    return `WEBVTT - Generated by Cinematic AI Voice Studio\n\n${body}`;
  }

  /**
   * Intelligent sentence-aware and rhythmic timing segmentation based on script and audio duration.
   * Splits into max ~2 line subtitles with natural breathing and pauses.
   */
  public generateSegmentsFromScript(
    script: string,
    totalDurationSec: number,
    pauseDurationMs: number = 800
  ): SubtitleSegment[] {
    const paragraphs = script
      .split(/\n+/)
      .map((p) => p.trim())
      .filter((p) => p.length > 0);

    if (paragraphs.length === 0) {
      return [];
    }

    // Split text into natural sentence/clause chunks (max 10-14 words or at punctuation)
    const rawChunks: { text: string; paragraphIndex: number }[] = [];

    paragraphs.forEach((p, pIdx) => {
      // Split by sentence terminators (. ! ? ;), keeping delimiters
      const sentences = p
        .replace(/([.!?]+)/g, '$1|')
        .split('|')
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      sentences.forEach((sentence) => {
        const words = sentence.split(/\s+/).filter(Boolean);
        if (words.length <= 12) {
          rawChunks.push({ text: sentence, paragraphIndex: pIdx });
        } else {
          // Break into 2 balanced lines / natural clauses
          const mid = Math.ceil(words.length / 2);
          const line1 = words.slice(0, mid).join(' ');
          const line2 = words.slice(mid).join(' ');
          rawChunks.push({ text: line1, paragraphIndex: pIdx });
          rawChunks.push({ text: line2, paragraphIndex: pIdx });
        }
      });
    });

    if (rawChunks.length === 0) return [];

    // Calculate relative phonetic weights based on characters and punctuation pauses
    const weights: number[] = rawChunks.map((chunk, idx) => {
      let weight = chunk.text.length + (chunk.text.split(/\s+/).length * 2);
      if (/[.!?]$/.test(chunk.text)) weight += 6;
      else if (/[,;:]$/.test(chunk.text)) weight += 3;

      // Add inter-paragraph pause weighting
      const isNextParagraph =
        idx < rawChunks.length - 1 && rawChunks[idx + 1].paragraphIndex !== chunk.paragraphIndex;
      if (isNextParagraph) {
        weight += (pauseDurationMs / 1000) * 15;
      }
      return Math.max(4, weight);
    });

    const totalWeight = weights.reduce((acc, w) => acc + w, 0);
    const effectiveDuration = Math.max(1, totalDurationSec);

    let currentTime = 0.15; // Lead-in
    const segments: SubtitleSegment[] = [];

    rawChunks.forEach((chunk, i) => {
      const chunkDuration = (weights[i] / totalWeight) * (effectiveDuration - 0.3);
      const isNextParagraph =
        i < rawChunks.length - 1 && rawChunks[i + 1].paragraphIndex !== chunk.paragraphIndex;
      
      const gap = isNextParagraph ? (pauseDurationMs / 1000) : 0.1;
      const start = Number(currentTime.toFixed(3));
      const end = Number(Math.min(effectiveDuration, currentTime + chunkDuration).toFixed(3));

      // Wrap text to max 2 lines if longer than 45 chars
      let formattedText = chunk.text;
      if (formattedText.length > 50 && !formattedText.includes('\n')) {
        const words = formattedText.split(' ');
        const halfway = Math.floor(words.length / 2);
        formattedText = `${words.slice(0, halfway).join(' ')}\n${words.slice(halfway).join(' ')}`;
      }

      segments.push({
        index: i + 1,
        start,
        end: Math.max(start + 0.5, end),
        text: formattedText,
      });

      currentTime = end + gap;
    });

    return segments;
  }

  /**
   * Main entry point to generate subtitles for a completed audio file.
   * Checks for Whisper binary/package first, then falls back seamlessly to sentence-aware alignment.
   */
  public async generateSubtitles(
    audioPath: string,
    jobId: string,
    script?: string,
    durationSeconds: number = 0,
    pauseDurationMs: number = 800
  ): Promise<SubtitleResult> {
    const srtFileName = `${jobId}.srt`;
    const vttFileName = `${jobId}.vtt`;
    const srtPath = path.join(CONFIG.SUBTITLES_DIR, srtFileName);
    const vttPath = path.join(CONFIG.SUBTITLES_DIR, vttFileName);

    let segments: SubtitleSegment[] = [];

    // 1. Try local Whisper CLI if available
    try {
      if (fs.existsSync(audioPath)) {
        const whisperCmd = `whisper "${audioPath}" --output_format srt --output_dir "${CONFIG.SUBTITLES_DIR}" --model tiny --language en`;
        await execAsync(whisperCmd, { timeout: 15000 });
        const generatedSrt = path.join(CONFIG.SUBTITLES_DIR, `${path.basename(audioPath, path.extname(audioPath))}.srt`);
        if (fs.existsSync(generatedSrt)) {
          if (generatedSrt !== srtPath) {
            fs.renameSync(generatedSrt, srtPath);
          }
          // Read and generate VTT
          const srtContent = fs.readFileSync(srtPath, 'utf-8');
          fs.writeFileSync(vttPath, `WEBVTT\n\n${srtContent.replace(/,/g, '.')}`, 'utf-8');
          return {
            srtPath,
            vttPath,
            srtUrl: `/uploads/subtitles/${srtFileName}`,
            vttUrl: `/uploads/subtitles/${vttFileName}`,
            segments: []
          };
        }
      }
    } catch (_) {
      // Whisper not installed locally or failed; proceed gracefully to intelligent script alignment
    }

    // 2. High-precision rhythmic and sentence-aware segmentation
    const textToAlign = script && script.trim().length > 0 ? script : 'Narrated Voiceover Track';
    const effectiveDuration = durationSeconds > 0 ? durationSeconds : Math.max(3, textToAlign.split(/\s+/).length / 2.5);

    segments = this.generateSegmentsFromScript(textToAlign, effectiveDuration, pauseDurationMs);

    const srtContent = this.generateSRT(segments);
    const vttContent = this.generateVTT(segments);

    fs.writeFileSync(srtPath, srtContent, 'utf-8');
    fs.writeFileSync(vttPath, vttContent, 'utf-8');

    return {
      srtPath,
      vttPath,
      srtUrl: `/uploads/subtitles/${srtFileName}`,
      vttUrl: `/uploads/subtitles/${vttFileName}`,
      segments,
    };
  }
}

export const subtitleService = new SubtitleService();
